version: '3.7'
services:
    source_db:
        image: postgres:14
        environment: 
          - POSTGRES_USER=test
          - POSTGRES_PASSWORD=test
          - POSTGRES_DB=source_db
        ports:
          - '6432:5432'